version: '3.2'
services:
   selenium:
      build:
        context: .
      image: artisticcheese/selenium:latest
      environment: 
        - "SHELL=powershell.exe"
      ports:
        - target: 4444
          published: 8181
          protocol: tcp
          mode: host
      networks: 
        - nat
networks: 
  nat:
    external: true