apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  labels:
    app: secret
    tier: middletier
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
        tier: middletier
    spec:
      containers:
        - name: secret-container
          image: mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
          env:
            - name: ConfigLocation
              value: c:\secret\web.config
          command:
            [
              'if ($env:ConfigLocation) {New-Item -Path C:\inetpub\wwwroot\Web.config -ItemType SymbolicLink -Value $env:ConfigLocation -force -Verbose}; & "C:\ServiceMonitor.exe" "w3svc"',
            ]
          volumeMounts:
            - name: secret
              mountPath: "secret"
      volumes:
        - name: secret
          secret:
            secretName: secretconfig
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  web.config: |
    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <location path="." inheritInChildApplications="false">
        <system.webServer>
          <handlers>
            <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
          </handlers>
          <aspNetCore processPath=".\MyApp.exe"
                      stdoutLogEnabled="false"
                      stdoutLogFile=".\logs\stdout"
                      hostingModel="inprocess" />
        </system.webServer>
      </location>
    </configuration>
