version: "2.3"
services:
  webapp:
    image: artisticcheese/legacyapp
    build: .
    networks:
      - nat
    ports:
      - "8080:80"
    cpu_count: 1
    cpu_percent: 10
    mem_limit: 1GB
    isolation: process

networks:
  nat:
    external: true
